// Known chess openings — name, SAN move sequence, reference URL, stats
// Stats: approximate win/draw/loss % for White from master games
// Longer (more specific) openings should come after their parent

export const OPENINGS = [
  // === KING'S PAWN (1.e4) ===

  // Italian / Giuoco Piano
  { name: "Italian Game", moves: ["e4","e5","Nf3","Nc6","Bc4"],
    url: "https://en.wikipedia.org/wiki/Italian_Game",
    stats: { w: 40, d: 32, b: 28 } },
  { name: "Giuoco Piano", moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5"],
    url: "https://en.wikipedia.org/wiki/Giuoco_Piano",
    stats: { w: 39, d: 33, b: 28 } },
  { name: "Giuoco Piano: Main Line", moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","c3"],
    url: "https://en.wikipedia.org/wiki/Giuoco_Piano#Main_line:_4.c3",
    stats: { w: 40, d: 32, b: 28 } },
  { name: "Giuoco Pianissimo", moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","d3"],
    url: "https://en.wikipedia.org/wiki/Giuoco_Piano#Giuoco_Pianissimo",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "Evans Gambit", moves: ["e4","e5","Nf3","Nc6","Bc4","Bc5","b4"],
    url: "https://en.wikipedia.org/wiki/Evans_Gambit",
    stats: { w: 44, d: 27, b: 29 } },
  { name: "Two Knights Defense", moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6"],
    url: "https://en.wikipedia.org/wiki/Two_Knights_Defense",
    stats: { w: 41, d: 30, b: 29 } },
  { name: "Fried Liver Attack", moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","d5","exd5","Nxd5","Nxf7"],
    url: "https://en.wikipedia.org/wiki/Fried_Liver_Attack",
    stats: { w: 53, d: 18, b: 29 } },
  { name: "Traxler Counterattack", moves: ["e4","e5","Nf3","Nc6","Bc4","Nf6","Ng5","Bc5"],
    url: "https://en.wikipedia.org/wiki/Traxler_Counterattack",
    stats: { w: 42, d: 22, b: 36 } },
  { name: "Hungarian Defense", moves: ["e4","e5","Nf3","Nc6","Bc4","Be7"],
    url: "https://en.wikipedia.org/wiki/Hungarian_Defense",
    stats: { w: 43, d: 30, b: 27 } },

  // Ruy López
  { name: "Ruy López", moves: ["e4","e5","Nf3","Nc6","Bb5"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez",
    stats: { w: 38, d: 35, b: 27 } },
  { name: "Ruy López: Berlin Defense", moves: ["e4","e5","Nf3","Nc6","Bb5","Nf6"],
    url: "https://en.wikipedia.org/wiki/Berlin_Defence_(chess)",
    stats: { w: 35, d: 40, b: 25 } },
  { name: "Ruy López: Morphy Defense", moves: ["e4","e5","Nf3","Nc6","Bb5","a6"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez#Morphy_Defence",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "Ruy López: Closed", moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez#Closed_Defence",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Ruy López: Marshall Attack", moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Ba4","Nf6","O-O","Be7","Re1","b5","Bb3","O-O","c3","d5"],
    url: "https://en.wikipedia.org/wiki/Marshall_Attack",
    stats: { w: 30, d: 42, b: 28 } },
  { name: "Ruy López: Exchange", moves: ["e4","e5","Nf3","Nc6","Bb5","a6","Bxc6"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez,_Exchange_Variation",
    stats: { w: 38, d: 36, b: 26 } },
  { name: "Ruy López: Classical", moves: ["e4","e5","Nf3","Nc6","Bb5","Bc5"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez#Classical_Defence:_3...Bc5",
    stats: { w: 40, d: 33, b: 27 } },
  { name: "Ruy López: Schliemann", moves: ["e4","e5","Nf3","Nc6","Bb5","f5"],
    url: "https://en.wikipedia.org/wiki/Schliemann_Defence",
    stats: { w: 43, d: 26, b: 31 } },
  { name: "Ruy López: Bird's Defense", moves: ["e4","e5","Nf3","Nc6","Bb5","Nd4"],
    url: "https://en.wikipedia.org/wiki/Ruy_Lopez#Bird's_Defence:_3...Nd4",
    stats: { w: 44, d: 28, b: 28 } },

  // Scotch
  { name: "Scotch Game", moves: ["e4","e5","Nf3","Nc6","d4"],
    url: "https://en.wikipedia.org/wiki/Scotch_Game",
    stats: { w: 40, d: 32, b: 28 } },
  { name: "Scotch Game: Classical", moves: ["e4","e5","Nf3","Nc6","d4","exd4","Nxd4","Bc5"],
    url: "https://en.wikipedia.org/wiki/Scotch_Game#Classical_Variation",
    stats: { w: 39, d: 33, b: 28 } },
  { name: "Scotch Gambit", moves: ["e4","e5","Nf3","Nc6","d4","exd4","Bc4"],
    url: "https://en.wikipedia.org/wiki/Scotch_Gambit",
    stats: { w: 42, d: 29, b: 29 } },
  { name: "Göring Gambit", moves: ["e4","e5","Nf3","Nc6","d4","exd4","c3"],
    url: "https://en.wikipedia.org/wiki/Scotch_Game#G%C3%B6ring_Gambit:_4.c3",
    stats: { w: 43, d: 26, b: 31 } },

  // Four Knights
  { name: "Four Knights Game", moves: ["e4","e5","Nf3","Nc6","Nc3","Nf6"],
    url: "https://en.wikipedia.org/wiki/Four_Knights_Game",
    stats: { w: 36, d: 38, b: 26 } },
  { name: "Four Knights: Spanish", moves: ["e4","e5","Nf3","Nc6","Nc3","Nf6","Bb5"],
    url: "https://en.wikipedia.org/wiki/Four_Knights_Game#Spanish_Variation",
    stats: { w: 37, d: 38, b: 25 } },
  { name: "Four Knights: Scotch", moves: ["e4","e5","Nf3","Nc6","Nc3","Nf6","d4"],
    url: "https://en.wikipedia.org/wiki/Four_Knights_Game#Scotch_Four_Knights",
    stats: { w: 38, d: 35, b: 27 } },

  // Petrov
  { name: "Petrov's Defense", moves: ["e4","e5","Nf3","Nf6"],
    url: "https://en.wikipedia.org/wiki/Petrov%27s_Defence",
    stats: { w: 35, d: 40, b: 25 } },
  { name: "Petrov: Classical", moves: ["e4","e5","Nf3","Nf6","Nxe5","d6","Nf3","Nxe4"],
    url: "https://en.wikipedia.org/wiki/Petrov%27s_Defence#Classical_Attack:_3.Nxe5",
    stats: { w: 34, d: 42, b: 24 } },
  { name: "Petrov: Steinitz", moves: ["e4","e5","Nf3","Nf6","d3"],
    url: "https://en.wikipedia.org/wiki/Petrov%27s_Defence#Steinitz_Attack:_3.d3",
    stats: { w: 36, d: 38, b: 26 } },

  // Philidor
  { name: "Philidor Defense", moves: ["e4","e5","Nf3","d6"],
    url: "https://en.wikipedia.org/wiki/Philidor_Defence",
    stats: { w: 44, d: 30, b: 26 } },
  { name: "Philidor: Hanham", moves: ["e4","e5","Nf3","d6","d4","Nd7"],
    url: "https://en.wikipedia.org/wiki/Philidor_Defence#Hanham_Variation",
    stats: { w: 44, d: 30, b: 26 } },

  // King's Gambit
  { name: "King's Gambit", moves: ["e4","e5","f4"],
    url: "https://en.wikipedia.org/wiki/King%27s_Gambit",
    stats: { w: 42, d: 26, b: 32 } },
  { name: "King's Gambit Accepted", moves: ["e4","e5","f4","exf4"],
    url: "https://en.wikipedia.org/wiki/King%27s_Gambit#King's_Gambit_Accepted",
    stats: { w: 43, d: 25, b: 32 } },
  { name: "King's Gambit Declined", moves: ["e4","e5","f4","Bc5"],
    url: "https://en.wikipedia.org/wiki/King%27s_Gambit#King's_Gambit_Declined:_2...Bc5",
    stats: { w: 40, d: 28, b: 32 } },
  { name: "Falkbeer Countergambit", moves: ["e4","e5","f4","d5"],
    url: "https://en.wikipedia.org/wiki/Falkbeer_Countergambit",
    stats: { w: 38, d: 28, b: 34 } },

  // Vienna
  { name: "Vienna Game", moves: ["e4","e5","Nc3"],
    url: "https://en.wikipedia.org/wiki/Vienna_Game",
    stats: { w: 39, d: 31, b: 30 } },
  { name: "Vienna Gambit", moves: ["e4","e5","Nc3","Nf6","f4"],
    url: "https://en.wikipedia.org/wiki/Vienna_Game#Vienna_Gambit:_2...Nf6_3.f4",
    stats: { w: 41, d: 28, b: 31 } },

  // Bishop's Opening
  { name: "Bishop's Opening", moves: ["e4","e5","Bc4"],
    url: "https://en.wikipedia.org/wiki/Bishop%27s_Opening",
    stats: { w: 39, d: 32, b: 29 } },

  // Center Game
  { name: "Center Game", moves: ["e4","e5","d4","exd4","Qxd4"],
    url: "https://en.wikipedia.org/wiki/Center_Game",
    stats: { w: 37, d: 31, b: 32 } },
  { name: "Danish Gambit", moves: ["e4","e5","d4","exd4","c3"],
    url: "https://en.wikipedia.org/wiki/Danish_Gambit",
    stats: { w: 44, d: 24, b: 32 } },

  // === SICILIAN (1.e4 c5) ===

  { name: "Sicilian Defense", moves: ["e4","c5"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence",
    stats: { w: 37, d: 30, b: 33 } },
  { name: "Sicilian: Open", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence#Open_Sicilian",
    stats: { w: 38, d: 29, b: 33 } },
  { name: "Sicilian: Najdorf", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Najdorf_Variation",
    stats: { w: 37, d: 30, b: 33 } },
  { name: "Sicilian: Najdorf English Attack", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","a6","Be3"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Najdorf_Variation#6.Be3_(English_Attack)",
    stats: { w: 38, d: 29, b: 33 } },
  { name: "Sicilian: Dragon", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Dragon_Variation",
    stats: { w: 40, d: 27, b: 33 } },
  { name: "Sicilian: Dragon Yugoslav Attack", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","g6","Be3","Bg7","f3"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Dragon_Variation,_Yugoslav_Attack",
    stats: { w: 42, d: 25, b: 33 } },
  { name: "Sicilian: Accelerated Dragon", moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","g6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Accelerated_Dragon",
    stats: { w: 39, d: 31, b: 30 } },
  { name: "Sicilian: Scheveningen", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","e6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Scheveningen_Variation",
    stats: { w: 39, d: 30, b: 31 } },
  { name: "Sicilian: Classical", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence#Classical_Variation",
    stats: { w: 38, d: 31, b: 31 } },
  { name: "Sicilian: Richter-Rauzer", moves: ["e4","c5","Nf3","d6","d4","cxd4","Nxd4","Nf6","Nc3","Nc6","Bg5"],
    url: "https://en.wikipedia.org/wiki/Richter%E2%80%93Rauzer_Attack",
    stats: { w: 39, d: 30, b: 31 } },
  { name: "Sicilian: Sveshnikov", moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","Nf6","Nc3","e5"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Sveshnikov_Variation",
    stats: { w: 37, d: 32, b: 31 } },
  { name: "Sicilian: Kalashnikov", moves: ["e4","c5","Nf3","Nc6","d4","cxd4","Nxd4","e5","Nb5","d6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Kalashnikov_Variation",
    stats: { w: 38, d: 31, b: 31 } },
  { name: "Sicilian: Taimanov", moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","Nc6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Taimanov_Variation",
    stats: { w: 38, d: 32, b: 30 } },
  { name: "Sicilian: Kan", moves: ["e4","c5","Nf3","e6","d4","cxd4","Nxd4","a6"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Kan_Variation",
    stats: { w: 39, d: 31, b: 30 } },
  { name: "Sicilian: Alapin", moves: ["e4","c5","c3"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Alapin_Variation",
    stats: { w: 40, d: 33, b: 27 } },
  { name: "Sicilian: Closed", moves: ["e4","c5","Nc3"],
    url: "https://en.wikipedia.org/wiki/Closed_Sicilian",
    stats: { w: 38, d: 32, b: 30 } },
  { name: "Sicilian: Grand Prix Attack", moves: ["e4","c5","Nc3","Nc6","f4"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence#Grand_Prix_Attack",
    stats: { w: 40, d: 30, b: 30 } },
  { name: "Sicilian: Smith-Morra Gambit", moves: ["e4","c5","d4","cxd4","c3"],
    url: "https://en.wikipedia.org/wiki/Smith%E2%80%93Morra_Gambit",
    stats: { w: 44, d: 25, b: 31 } },
  { name: "Sicilian: Rossolimo", moves: ["e4","c5","Nf3","Nc6","Bb5"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Rossolimo_Variation",
    stats: { w: 39, d: 34, b: 27 } },
  { name: "Sicilian: Moscow", moves: ["e4","c5","Nf3","d6","Bb5+"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Moscow_Variation",
    stats: { w: 40, d: 33, b: 27 } },
  { name: "Sicilian: Wing Gambit", moves: ["e4","c5","b4"],
    url: "https://en.wikipedia.org/wiki/Sicilian_Defence,_Wing_Gambit",
    stats: { w: 38, d: 25, b: 37 } },

  // === FRENCH (1.e4 e6) ===

  { name: "French Defense", moves: ["e4","e6"],
    url: "https://en.wikipedia.org/wiki/French_Defence",
    stats: { w: 38, d: 33, b: 29 } },
  { name: "French: Winawer", moves: ["e4","e6","d4","d5","Nc3","Bb4"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Winawer_Variation",
    stats: { w: 38, d: 31, b: 31 } },
  { name: "French: Winawer Poisoned Pawn", moves: ["e4","e6","d4","d5","Nc3","Bb4","e5","c5","a3","Bxc3+","bxc3","Ne7","Qg4"],
    url: "https://en.wikipedia.org/wiki/French_Defence,_Winawer_Variation#Poisoned_Pawn_Variation",
    stats: { w: 39, d: 30, b: 31 } },
  { name: "French: Classical", moves: ["e4","e6","d4","d5","Nc3","Nf6"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Classical_Variation",
    stats: { w: 38, d: 33, b: 29 } },
  { name: "French: Burn", moves: ["e4","e6","d4","d5","Nc3","Nf6","Bg5","dxe4"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Burn_Variation:_4.Bg5_dxe4",
    stats: { w: 37, d: 34, b: 29 } },
  { name: "French: Tarrasch", moves: ["e4","e6","d4","d5","Nd2"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Tarrasch_Variation",
    stats: { w: 37, d: 35, b: 28 } },
  { name: "French: Advance", moves: ["e4","e6","d4","d5","e5"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Advance_Variation",
    stats: { w: 37, d: 34, b: 29 } },
  { name: "French: Exchange", moves: ["e4","e6","d4","d5","exd5"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Exchange_Variation",
    stats: { w: 36, d: 39, b: 25 } },
  { name: "French: Rubinstein", moves: ["e4","e6","d4","d5","Nc3","dxe4","Nxe4"],
    url: "https://en.wikipedia.org/wiki/French_Defence#Rubinstein_Variation:_3...dxe4",
    stats: { w: 40, d: 34, b: 26 } },
  { name: "French: King's Indian Attack", moves: ["e4","e6","d3"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Attack",
    stats: { w: 38, d: 33, b: 29 } },

  // === CARO-KANN (1.e4 c6) ===

  { name: "Caro-Kann Defense", moves: ["e4","c6"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence",
    stats: { w: 38, d: 35, b: 27 } },
  { name: "Caro-Kann: Advance", moves: ["e4","c6","d4","d5","e5"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence#Advance_Variation",
    stats: { w: 39, d: 33, b: 28 } },
  { name: "Caro-Kann: Classical", moves: ["e4","c6","d4","d5","Nc3","dxe4","Nxe4","Bf5"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence#Classical_Variation",
    stats: { w: 36, d: 37, b: 27 } },
  { name: "Caro-Kann: Exchange", moves: ["e4","c6","d4","d5","exd5","cxd5"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence#Exchange_Variation",
    stats: { w: 37, d: 38, b: 25 } },
  { name: "Caro-Kann: Panov-Botvinnik", moves: ["e4","c6","d4","d5","exd5","cxd5","c4"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence,_Panov%E2%80%93Botvinnik_Attack",
    stats: { w: 39, d: 34, b: 27 } },
  { name: "Caro-Kann: Two Knights", moves: ["e4","c6","Nc3","d5","Nf3"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence#Two_Knights_Variation",
    stats: { w: 40, d: 32, b: 28 } },
  { name: "Caro-Kann: Fantasy", moves: ["e4","c6","d4","d5","f3"],
    url: "https://en.wikipedia.org/wiki/Caro%E2%80%93Kann_Defence#Fantasy_Variation:_3.f3",
    stats: { w: 42, d: 28, b: 30 } },

  // === PIRC / MODERN ===

  { name: "Pirc Defense", moves: ["e4","d6"],
    url: "https://en.wikipedia.org/wiki/Pirc_Defence",
    stats: { w: 44, d: 28, b: 28 } },
  { name: "Pirc: Classical", moves: ["e4","d6","d4","Nf6","Nc3","g6","Nf3"],
    url: "https://en.wikipedia.org/wiki/Pirc_Defence#Classical_(Two_Knights)_System",
    stats: { w: 43, d: 29, b: 28 } },
  { name: "Pirc: Austrian Attack", moves: ["e4","d6","d4","Nf6","Nc3","g6","f4"],
    url: "https://en.wikipedia.org/wiki/Pirc_Defence#Austrian_Attack:_4.f4",
    stats: { w: 44, d: 26, b: 30 } },
  { name: "Modern Defense", moves: ["e4","g6"],
    url: "https://en.wikipedia.org/wiki/Modern_Defense",
    stats: { w: 46, d: 27, b: 27 } },

  // === SCANDINAVIAN ===

  { name: "Scandinavian Defense", moves: ["e4","d5"],
    url: "https://en.wikipedia.org/wiki/Scandinavian_Defense",
    stats: { w: 43, d: 30, b: 27 } },
  { name: "Scandinavian: Main Line", moves: ["e4","d5","exd5","Qxd5","Nc3","Qa5"],
    url: "https://en.wikipedia.org/wiki/Scandinavian_Defense#2...Qxd5",
    stats: { w: 42, d: 31, b: 27 } },
  { name: "Scandinavian: Modern", moves: ["e4","d5","exd5","Nf6"],
    url: "https://en.wikipedia.org/wiki/Scandinavian_Defense#2...Nf6",
    stats: { w: 44, d: 28, b: 28 } },

  // === ALEKHINE ===

  { name: "Alekhine's Defense", moves: ["e4","Nf6"],
    url: "https://en.wikipedia.org/wiki/Alekhine%27s_Defence",
    stats: { w: 42, d: 30, b: 28 } },
  { name: "Alekhine: Four Pawns Attack", moves: ["e4","Nf6","e5","Nd5","d4","d6","c4","Nb6","f4"],
    url: "https://en.wikipedia.org/wiki/Alekhine%27s_Defence#Four_Pawns_Attack:_5.f4",
    stats: { w: 43, d: 27, b: 30 } },
  { name: "Alekhine: Modern", moves: ["e4","Nf6","e5","Nd5","d4","d6","Nf3"],
    url: "https://en.wikipedia.org/wiki/Alekhine%27s_Defence#Modern_Variation:_4.Nf3",
    stats: { w: 41, d: 31, b: 28 } },

  // === OTHER e4 RESPONSES ===

  { name: "Owen's Defense", moves: ["e4","b6"],
    url: "https://en.wikipedia.org/wiki/Owen%27s_Defence",
    stats: { w: 48, d: 24, b: 28 } },
  { name: "Nimzowitsch Defense", moves: ["e4","Nc6"],
    url: "https://en.wikipedia.org/wiki/Nimzowitsch_Defence",
    stats: { w: 46, d: 26, b: 28 } },
  { name: "St. George Defense", moves: ["e4","a6"],
    url: "https://en.wikipedia.org/wiki/St._George_Defence",
    stats: { w: 48, d: 24, b: 28 } },

  // === QUEEN'S PAWN (1.d4) ===

  // Queen's Gambit
  { name: "Queen's Gambit", moves: ["d4","d5","c4"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit",
    stats: { w: 39, d: 36, b: 25 } },
  { name: "Queen's Gambit Declined", moves: ["d4","d5","c4","e6"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined",
    stats: { w: 38, d: 37, b: 25 } },
  { name: "QGD: Orthodox", moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Be7","e3","O-O","Nf3"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined#Orthodox_Defence",
    stats: { w: 37, d: 38, b: 25 } },
  { name: "QGD: Tartakower", moves: ["d4","d5","c4","e6","Nc3","Nf6","Bg5","Be7","e3","O-O","Nf3","b6"],
    url: "https://en.wikipedia.org/wiki/Tartakower_Variation",
    stats: { w: 36, d: 38, b: 26 } },
  { name: "QGD: Ragozin", moves: ["d4","d5","c4","e6","Nc3","Nf6","Nf3","Bb4"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined,_Ragozin_Defence",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "QGD: Vienna", moves: ["d4","d5","c4","e6","Nf3","Nf6","Nc3","dxc4"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined#Vienna_Variation",
    stats: { w: 38, d: 36, b: 26 } },
  { name: "Queen's Gambit Accepted", moves: ["d4","d5","c4","dxc4"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Accepted",
    stats: { w: 40, d: 34, b: 26 } },
  { name: "QGA: Classical", moves: ["d4","d5","c4","dxc4","Nf3","Nf6","e3","e6"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Accepted#Classical_Variation",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "Slav Defense", moves: ["d4","d5","c4","c6"],
    url: "https://en.wikipedia.org/wiki/Slav_Defense",
    stats: { w: 37, d: 37, b: 26 } },
  { name: "Slav: Main Line", moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","dxc4"],
    url: "https://en.wikipedia.org/wiki/Slav_Defense#Main_Line:_4...dxc4",
    stats: { w: 37, d: 37, b: 26 } },
  { name: "Semi-Slav Defense", moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","e6"],
    url: "https://en.wikipedia.org/wiki/Semi-Slav_Defense",
    stats: { w: 36, d: 38, b: 26 } },
  { name: "Semi-Slav: Meran", moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","e6","e3","Nbd7","Bd3","dxc4","Bxc4","b5"],
    url: "https://en.wikipedia.org/wiki/Semi-Slav_Defense#Meran_Variation",
    stats: { w: 36, d: 37, b: 27 } },
  { name: "Semi-Slav: Botvinnik", moves: ["d4","d5","c4","c6","Nf3","Nf6","Nc3","e6","Bg5","dxc4","e4","b5"],
    url: "https://en.wikipedia.org/wiki/Semi-Slav_Defense#Anti-Meran:_Botvinnik_System",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "Albin Countergambit", moves: ["d4","d5","c4","e5"],
    url: "https://en.wikipedia.org/wiki/Albin_Countergambit",
    stats: { w: 42, d: 30, b: 28 } },
  { name: "Chigorin Defense", moves: ["d4","d5","c4","Nc6"],
    url: "https://en.wikipedia.org/wiki/Chigorin_Defense",
    stats: { w: 42, d: 30, b: 28 } },
  { name: "Baltic Defense", moves: ["d4","d5","c4","Bf5"],
    url: "https://en.wikipedia.org/wiki/Baltic_Defense",
    stats: { w: 44, d: 28, b: 28 } },

  // Indian Defenses
  { name: "King's Indian Defense", moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence",
    stats: { w: 40, d: 30, b: 30 } },
  { name: "KID: Classical", moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Nf3","O-O","Be2","e5"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence,_Classical_Variation",
    stats: { w: 39, d: 31, b: 30 } },
  { name: "KID: Sämisch", moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f3"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence,_S%C3%A4misch_Variation",
    stats: { w: 41, d: 29, b: 30 } },
  { name: "KID: Four Pawns Attack", moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","f4"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence,_Four_Pawns_Attack",
    stats: { w: 42, d: 27, b: 31 } },
  { name: "KID: Averbakh", moves: ["d4","Nf6","c4","g6","Nc3","Bg7","e4","d6","Be2","O-O","Bg5"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence,_Averbakh_Variation",
    stats: { w: 40, d: 32, b: 28 } },
  { name: "Grünfeld Defense", moves: ["d4","Nf6","c4","g6","Nc3","d5"],
    url: "https://en.wikipedia.org/wiki/Gr%C3%BCnfeld_Defence",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "Grünfeld: Exchange", moves: ["d4","Nf6","c4","g6","Nc3","d5","cxd5","Nxd5","e4"],
    url: "https://en.wikipedia.org/wiki/Gr%C3%BCnfeld_Defence,_Exchange_Variation",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "Grünfeld: Russian", moves: ["d4","Nf6","c4","g6","Nc3","d5","Nf3","Bg7","Qb3"],
    url: "https://en.wikipedia.org/wiki/Gr%C3%BCnfeld_Defence#Russian_System",
    stats: { w: 37, d: 35, b: 28 } },
  { name: "Nimzo-Indian Defense", moves: ["d4","Nf6","c4","e6","Nc3","Bb4"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Nimzo-Indian: Rubinstein", moves: ["d4","Nf6","c4","e6","Nc3","Bb4","e3"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence#Rubinstein_Variation:_4.e3",
    stats: { w: 37, d: 37, b: 26 } },
  { name: "Nimzo-Indian: Classical", moves: ["d4","Nf6","c4","e6","Nc3","Bb4","Qc2"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence#Classical_Variation:_4.Qc2",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Nimzo-Indian: Sämisch", moves: ["d4","Nf6","c4","e6","Nc3","Bb4","a3"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence#S%C3%A4misch_Variation:_4.a3",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "Nimzo-Indian: Leningrad", moves: ["d4","Nf6","c4","e6","Nc3","Bb4","Bg5"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence#Leningrad_Variation:_4.Bg5",
    stats: { w: 38, d: 35, b: 27 } },
  { name: "Queen's Indian Defense", moves: ["d4","Nf6","c4","e6","Nf3","b6"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Indian_Defense",
    stats: { w: 38, d: 37, b: 25 } },
  { name: "Bogo-Indian Defense", moves: ["d4","Nf6","c4","e6","Nf3","Bb4+"],
    url: "https://en.wikipedia.org/wiki/Bogo-Indian_Defence",
    stats: { w: 38, d: 37, b: 25 } },
  { name: "Catalan Opening", moves: ["d4","Nf6","c4","e6","g3"],
    url: "https://en.wikipedia.org/wiki/Catalan_Opening",
    stats: { w: 40, d: 36, b: 24 } },
  { name: "Catalan: Open", moves: ["d4","Nf6","c4","e6","g3","d5","Bg2","dxc4"],
    url: "https://en.wikipedia.org/wiki/Catalan_Opening#Open_Catalan",
    stats: { w: 41, d: 35, b: 24 } },
  { name: "Catalan: Closed", moves: ["d4","Nf6","c4","e6","g3","d5","Bg2","Be7"],
    url: "https://en.wikipedia.org/wiki/Catalan_Opening#Closed_Catalan",
    stats: { w: 39, d: 37, b: 24 } },
  { name: "Benoni Defense", moves: ["d4","Nf6","c4","c5","d5"],
    url: "https://en.wikipedia.org/wiki/Benoni_Defense",
    stats: { w: 42, d: 28, b: 30 } },
  { name: "Modern Benoni", moves: ["d4","Nf6","c4","c5","d5","e6","Nc3","exd5","cxd5","d6"],
    url: "https://en.wikipedia.org/wiki/Modern_Benoni",
    stats: { w: 42, d: 27, b: 31 } },
  { name: "Benko Gambit", moves: ["d4","Nf6","c4","c5","d5","b5"],
    url: "https://en.wikipedia.org/wiki/Benko_Gambit",
    stats: { w: 38, d: 32, b: 30 } },
  { name: "Budapest Gambit", moves: ["d4","Nf6","c4","e5"],
    url: "https://en.wikipedia.org/wiki/Budapest_Gambit",
    stats: { w: 42, d: 30, b: 28 } },
  { name: "Old Indian Defense", moves: ["d4","Nf6","c4","d6","Nc3","e5"],
    url: "https://en.wikipedia.org/wiki/Old_Indian_Defense",
    stats: { w: 42, d: 30, b: 28 } },

  // d4 e6 move orders
  { name: "Horwitz Defense", moves: ["d4","e6"],
    url: "https://en.wikipedia.org/wiki/Horwitz_Defense",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "Queen's Gambit Declined", moves: ["d4","e6","c4","d5"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Gambit_Declined",
    stats: { w: 38, d: 37, b: 25 } },
  { name: "Nimzo-Indian Defense", moves: ["d4","e6","c4","Nf6","Nc3","Bb4"],
    url: "https://en.wikipedia.org/wiki/Nimzo-Indian_Defence",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Queen's Indian Defense", moves: ["d4","e6","c4","Nf6","Nf3","b6"],
    url: "https://en.wikipedia.org/wiki/Queen%27s_Indian_Defense",
    stats: { w: 38, d: 37, b: 25 } },
  { name: "Catalan Opening", moves: ["d4","e6","c4","Nf6","g3"],
    url: "https://en.wikipedia.org/wiki/Catalan_Opening",
    stats: { w: 40, d: 36, b: 24 } },
  { name: "Bogo-Indian Defense", moves: ["d4","e6","c4","Nf6","Nf3","Bb4+"],
    url: "https://en.wikipedia.org/wiki/Bogo-Indian_Defence",
    stats: { w: 38, d: 37, b: 25 } },

  // Dutch
  { name: "Dutch Defense", moves: ["d4","f5"],
    url: "https://en.wikipedia.org/wiki/Dutch_Defence",
    stats: { w: 42, d: 28, b: 30 } },
  { name: "Dutch: Stonewall", moves: ["d4","f5","c4","Nf6","g3","e6","Bg2","d5"],
    url: "https://en.wikipedia.org/wiki/Dutch_Defence#Stonewall_Variation",
    stats: { w: 40, d: 30, b: 30 } },
  { name: "Dutch: Leningrad", moves: ["d4","f5","c4","Nf6","g3","g6"],
    url: "https://en.wikipedia.org/wiki/Dutch_Defence#Leningrad_Variation",
    stats: { w: 41, d: 29, b: 30 } },
  { name: "Dutch: Classical", moves: ["d4","f5","c4","Nf6","g3","e6","Bg2","Be7"],
    url: "https://en.wikipedia.org/wiki/Dutch_Defence#Classical_Variation",
    stats: { w: 41, d: 30, b: 29 } },

  // London / Torre / Colle
  { name: "London System", moves: ["d4","d5","Nf3","Nf6","Bf4"],
    url: "https://en.wikipedia.org/wiki/London_System",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "London System", moves: ["d4","Nf6","Nf3","d5","Bf4"],
    url: "https://en.wikipedia.org/wiki/London_System",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "London System", moves: ["d4","Nf6","Bf4"],
    url: "https://en.wikipedia.org/wiki/London_System",
    stats: { w: 39, d: 35, b: 26 } },
  { name: "Torre Attack", moves: ["d4","Nf6","Nf3","e6","Bg5"],
    url: "https://en.wikipedia.org/wiki/Torre_Attack",
    stats: { w: 38, d: 35, b: 27 } },
  { name: "Colle System", moves: ["d4","d5","Nf3","Nf6","e3"],
    url: "https://en.wikipedia.org/wiki/Colle_System",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Colle-Zukertort", moves: ["d4","d5","Nf3","Nf6","e3","e6","Bd3","c5","b3"],
    url: "https://en.wikipedia.org/wiki/Colle_System#Colle%E2%80%93Zukertort_system",
    stats: { w: 38, d: 35, b: 27 } },
  { name: "Trompowsky Attack", moves: ["d4","Nf6","Bg5"],
    url: "https://en.wikipedia.org/wiki/Trompowsky_Attack",
    stats: { w: 41, d: 31, b: 28 } },
  { name: "Veresov Opening", moves: ["d4","Nf6","Nc3","d5","Bg5"],
    url: "https://en.wikipedia.org/wiki/Richter%E2%80%93Veresov_Attack",
    stats: { w: 40, d: 30, b: 30 } },
  { name: "Blackmar-Diemer Gambit", moves: ["d4","d5","e4","dxe4","Nc3"],
    url: "https://en.wikipedia.org/wiki/Blackmar%E2%80%93Diemer_Gambit",
    stats: { w: 44, d: 22, b: 34 } },

  // === ENGLISH (1.c4) ===

  { name: "English Opening", moves: ["c4"],
    url: "https://en.wikipedia.org/wiki/English_Opening",
    stats: { w: 37, d: 35, b: 28 } },
  { name: "English: Symmetrical", moves: ["c4","c5"],
    url: "https://en.wikipedia.org/wiki/English_Opening#Symmetrical_Variation",
    stats: { w: 36, d: 37, b: 27 } },
  { name: "English: Reversed Sicilian", moves: ["c4","e5"],
    url: "https://en.wikipedia.org/wiki/English_Opening#Reversed_Sicilian",
    stats: { w: 37, d: 34, b: 29 } },
  { name: "English: Anglo-Indian", moves: ["c4","Nf6"],
    url: "https://en.wikipedia.org/wiki/English_Opening#1...Nf6:_Anglo-Indian_Defence",
    stats: { w: 37, d: 35, b: 28 } },
  { name: "English: Caro-Kann", moves: ["c4","c6"],
    url: "https://en.wikipedia.org/wiki/English_Opening#1...c6",
    stats: { w: 38, d: 34, b: 28 } },
  { name: "English: Four Knights", moves: ["c4","e5","Nc3","Nf6","Nf3","Nc6"],
    url: "https://en.wikipedia.org/wiki/English_Opening,_Four_Knights_Variation",
    stats: { w: 36, d: 37, b: 27 } },
  { name: "English: Botvinnik", moves: ["c4","e5","Nc3","Nf6","g3","d5","cxd5","Nxd5","Bg2"],
    url: "https://en.wikipedia.org/wiki/English_Opening#Botvinnik_System",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "English: Hedgehog", moves: ["c4","c5","Nf3","Nf6","g3","b6","Bg2","Bb7","O-O","e6"],
    url: "https://en.wikipedia.org/wiki/Hedgehog_(chess)",
    stats: { w: 36, d: 37, b: 27 } },

  // === RÉTI (1.Nf3) ===

  { name: "Réti Opening", moves: ["Nf3","d5"],
    url: "https://en.wikipedia.org/wiki/R%C3%A9ti_Opening",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Réti: King's Indian Attack", moves: ["Nf3","d5","g3"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Attack",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Réti Gambit", moves: ["Nf3","d5","c4"],
    url: "https://en.wikipedia.org/wiki/R%C3%A9ti_Opening",
    stats: { w: 38, d: 36, b: 26 } },
  { name: "Réti: Advance", moves: ["Nf3","d5","c4","d4"],
    url: "https://en.wikipedia.org/wiki/R%C3%A9ti_Opening#1...d5_2.c4_d4",
    stats: { w: 38, d: 34, b: 28 } },

  // === OTHER FIRST MOVES ===

  { name: "Bird's Opening", moves: ["f4"],
    url: "https://en.wikipedia.org/wiki/Bird%27s_Opening",
    stats: { w: 36, d: 28, b: 36 } },
  { name: "Bird: From's Gambit", moves: ["f4","e5"],
    url: "https://en.wikipedia.org/wiki/From%27s_Gambit",
    stats: { w: 34, d: 26, b: 40 } },
  { name: "Bird: Dutch", moves: ["f4","d5"],
    url: "https://en.wikipedia.org/wiki/Bird%27s_Opening#1...d5",
    stats: { w: 37, d: 29, b: 34 } },
  { name: "Larsen's Opening", moves: ["b3"],
    url: "https://en.wikipedia.org/wiki/Larsen%27s_Opening",
    stats: { w: 37, d: 30, b: 33 } },
  { name: "Sokolsky Opening", moves: ["b4"],
    url: "https://en.wikipedia.org/wiki/Sokolsky_Opening",
    stats: { w: 36, d: 28, b: 36 } },
  { name: "King's Indian Attack", moves: ["Nf3","d5","g3","Nf6","Bg2"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Attack",
    stats: { w: 37, d: 36, b: 27 } },
  { name: "Grob's Attack", moves: ["g4"],
    url: "https://en.wikipedia.org/wiki/Grob%27s_Attack",
    stats: { w: 32, d: 24, b: 44 } },
  { name: "Bongcloud Attack", moves: ["e4","e5","Ke2"],
    url: "https://en.wikipedia.org/wiki/Bongcloud_Attack",
    stats: { w: 25, d: 15, b: 60 } },

  // === d4 d6 / d4 g6 ===

  { name: "King's Indian: Normal", moves: ["d4","Nf6","c4","g6"],
    url: "https://en.wikipedia.org/wiki/King%27s_Indian_Defence",
    stats: { w: 40, d: 31, b: 29 } },
  { name: "Modern Defense", moves: ["d4","g6"],
    url: "https://en.wikipedia.org/wiki/Modern_Defense",
    stats: { w: 44, d: 28, b: 28 } },
  { name: "Pirc: d4 move order", moves: ["d4","d6"],
    url: "https://en.wikipedia.org/wiki/Pirc_Defence",
    stats: { w: 44, d: 28, b: 28 } },
];
